version: 2
jobs:
  example:
  working_directory: /work
  docker:
    - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: submodule update and execute
          command: |
            git submodule foreach git pull origin master
            apk add --update python &&  rm -rf /var/cache/apk/*
            python main.py

