version: 2
jobs:
  build:
    working_directory: /work_space
    docker:
      - image: docker:17.05.0-ce-git

    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: submodule update and execute
          command: |
            git submodule init
            git submodule update
            git submodule foreach git pull origin master
            apk add --update python &&  rm -rf /var/cache/apk/*
            python main.py
